# Generated by Django 5.0.7 on 2024-07-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardPrime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
