# Generated by Django 5.0.7 on 2024-07-26 23:26

import django.db.models.deletion
import rewardPrime.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewardPrime', '0002_alter_character_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('skill', models.TextField(default='Unknown', max_length=200, validators=[rewardPrime.validators.isAdviceValidated])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewardPrime.bounty')),
                ('hunter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewardPrime.hunter')),
            ],
        ),
    ]
